services:
  vpn-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      vpn-net:
        ipv4_address: 192.168.1.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    depends_on:
      - vpn-server
    # command: sh -c "go run client.go"
    command: sh -c "tcpdump -i eth0 -w /tmp/client_eth0_traffic.pcap & go run client.go"
    volumes:
      - ./client/pcaps:/tmp

  vpn-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      vpn-net:
        ipv4_address: 192.168.1.50
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    # command: >
    #   sh -c "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE && ./vpn-server"
    command: >
      sh -c "tcpdump -i eth0 -w /tmp/server_eth0_traffic.pcap & iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE && ./vpn-server"
    volumes:
      - ./server/pcaps:/tmp

  # web-server:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   networks:
  #     vpn-net:
  #       ipv4_address: 192.168.1.78
  #   ports:
  #     - "8080:80"

networks:
  vpn-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24